device_id: rpi-01
labels: ["zone-a", "rpi"]
modules:
  ndi:
    # Choose and customize commands for your environment. Example uses yuri2 + ffmpeg.
    start_cmd_template: 'yuri_simple ndi_input[stream="{source}"] glx_window[fullscreen=True]'
    stop_cmd: 'pkill -f "yuri_simple"'
    set_input_restart: true
    record_start_cmd_template: '/usr/local/bin/ffmpeg -y -f libndi_newtek -i "{source}" -c copy /home/pi/ndi_{device_id}.mp4'
    record_stop_cmd: 'pkill -INT ffmpeg'
mqtt:
  host: 127.0.0.1
  port: 1883
  username: device-led-ndi
  password: devpass
